spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v1
        cluster-name: BEIJING
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          #           rocketmq 必须设置
          group: binder-group
  #        namespace:  5aee0e1b-51f7-414b-908b-c773f389b047
  #      cluster-name: BEIJING
  application:
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
#      抽样率不丢失任何数据达到100%
#      建议默认0.1不会影响性能
      probability: 1.0
mybatis:
  mapper-locations: classpath:/mapper/**Mapper.xml
server:
  port: 8081
#rocketmq:
#  name-server: 127.0.1:9876
jwt:
  secret: fafasdfsdfasdfasdffadsfdasfasdfas
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always